name: addons
replicaCount: 1
image:
  name: add-ons-ui
  pullPolicy: IfNotPresent
  version: 3c504c2d
service:
  internalPort: 80
  externalPort: 80
  protocol: TCP
virtualservice:
  enabled: true
  annotations: {}
resources: {}
